# Broadcast
from util.network_util import get_broadcast_address

BROADCAST_PORT = 12345
BROADCAST_ADDRESS = get_broadcast_address()
BROADCAST_TIMEOUT = 8
HEART_BEAT_INTERVAL = 20
HEART_BEAT_TIMEOUT = 60
CLIENT_WAIT_INTERVAL = 60
DISCOVERY_TIMEOUT = 60
MAX_MISSED_HEART_BEATS = 2

# UNICAST
UNICAST_TIMEOUT = 3

# Localhost
SERVER_ADDRESS = "0.0.0.0"

CLIENT = "client"
SERVER = "server"

# Request Response Payloads
DISCOVERY_REQUEST = "DISCOVERY_REQUEST"
DISCOVERY_RESPONSE = "DISCOVERY_RESPONSE"
LEADER_ELECTION_REQUEST = "LEADER_ELECTION_REQUEST"
LEADER_ELECTION_RESPONSE = "LEADER_ELECTION_RESPONSE"
LEADER_ACK_RESPONSE = "LEADER_ACK_RESPONSE"
LEADER_ELECTION_COORDINATION_REQUEST = "LEADER_ELECTION_COORDINATION_REQUEST"
HEART_BEAT = "HEART_BEAT"
HEART_BEAT_ACK = "HEART_BEAT_ACK"
REASSIGNMENT = "REASSIGNMENT"
LEADER_DETAILS = "LEADER_DETAILS"
STATE_REPLICATE = "STATE_REPLICATE"
STATE_REPLICATION_REQUEST = "STATE_REPLICATION_REQUEST"

# Replication settings
REPLICATION_INTERVAL = 5  # Seconds between periodic state replication

# Auction Creation & Joining
AUCTION_CREATE_REQUEST = "AUCTION_CREATE_REQUEST"
AUCTION_CREATE_ACK = "AUCTION_CREATE_ACK"
AUCTION_CREATE_DENY = "AUCTION_CREATE_DENY"
AUCTION_LIST_REQUEST = "AUCTION_LIST_REQUEST"
AUCTION_LIST_RESPONSE = "AUCTION_LIST_RESPONSE"
AUCTION_JOIN_REQUEST = "AUCTION_JOIN_REQUEST"
AUCTION_JOIN_ACK = "AUCTION_JOIN_ACK"
AUCTION_JOIN_DENY = "AUCTION_JOIN_DENY"

# Auction Lifecycle
AUCTION_READY_CHECK = "AUCTION_READY_CHECK"
AUCTION_READY_CONFIRM = "AUCTION_READY_CONFIRM"
AUCTION_START = "AUCTION_START"
AUCTION_CANCEL = "AUCTION_CANCEL"
AUCTION_START_TIMEOUT = 60  # Seconds to wait for auctioneer to confirm start

# Bidding
ROUND_START = "ROUND_START"
BID_SUBMIT = "BID_SUBMIT"
BID_SUBMIT_RETRANSMIT = "BID_SUBMIT_RETRANSMIT"
BID_BROADCAST = "BID_BROADCAST"
ROUND_COMPLETE = "ROUND_COMPLETE"

# Completion
AUCTION_WINNER = "AUCTION_WINNER"
AUCTION_LOSER = "AUCTION_LOSER"
AUCTION_RESULT = "AUCTION_RESULT"
